'use strict';
const REPO='m13nbeauty/MN13',BRANCH='main',DATA_PATH='MN13/content.json',DRAFT_KEY='mn13-content-draft-v1';
let data,tab='courses',selected=null,token='',baseSha=null,dirty=false,busy=false,baseline='';
const uploads=new Map(),$=selector=>document.querySelector(selector);
function node(tag,value,cls){const n=document.createElement(tag);if(value!==undefined)n.textContent=value;if(cls)n.className=cls;return n}
function status(message){$('#status').textContent=message}
function setBusy(value){busy=value;document.querySelectorAll('button,input,textarea').forEach(n=>n.disabled=value)}
function safeImage(value){if(typeof value!=='string')return false;if(/^data:image\/(png|jpeg|webp);base64,/.test(value))return true;try{const u=new URL(value,location.href);return u.protocol==='https:'||u.origin===location.origin&&u.protocol==='http:'}catch{return false}}
function current(){return data?.[tab].find(item=>item.id===selected)}
function changed(){dirty=true;status('有尚未發布的修改。');renderList()}
function renderList(){const list=$('#list'),query=$('#search').value.trim().toLowerCase();list.replaceChildren();if(!data)return;[...data[tab]].sort((a,b)=>a.sortOrder-b.sortOrder).filter(i=>(i.title+' '+(i.category||i.tags?.join(' ')||'')).toLowerCase().includes(query)).forEach(item=>{const b=node('button');b.type='button';b.setAttribute('aria-current',String(item.id===selected));b.append(node('span',item.title||'未命名'),node('small',(item.visible?'顯示':'隱藏')+' · '+(item.category||item.tags?.join(' / ')||'肌膚日誌')));b.onclick=()=>{selected=item.id;renderList();renderEditor()};list.append(b)})}
function field(form,item,key,label,type='text',hint=''){const wrap=node('label',label);if(hint)wrap.append(node('small',hint));const input=document.createElement(type==='textarea'?'textarea':'input');if(type!=='textarea')input.type=type;input.value=item[key]??'';input.name=key;input.oninput=()=>{item[key]=type==='number'?Number(input.value):input.value;changed()};wrap.append(input);form.append(wrap);return input}
function checkbox(form,item,key,label){const wrap=node('label'),input=document.createElement('input');input.type='checkbox';input.name=key;input.checked=item[key]===true;input.onchange=()=>{item[key]=input.checked;changed()};wrap.append(input,document.createTextNode(label));form.append(wrap)}
function imageEditor(form,item,key,label,multiple){const wrap=node('section'),heading=node('label',label),file=document.createElement('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';file.multiple=multiple;heading.append(node('small','上傳 PNG、JPG 或 WebP，單張上限 8 MB。圖片直接保存原檔。'));heading.append(file);wrap.append(heading);const preview=node('div',undefined,'image-preview');wrap.append(preview);function draw(){preview.replaceChildren();const values=multiple?item[key]||[]:item[key]?[item[key]]:[];values.forEach((src,index)=>{const figure=node('figure'),im=document.createElement('img');if(safeImage(src))im.src=src;im.alt=label+' '+(index+1);im.draggable=false;const remove=node('button','移除');remove.type='button';remove.onclick=()=>{if(multiple)item[key].splice(index,1);else item[key]='';changed();draw()};figure.append(im,remove);preview.append(figure)})}draw();file.onchange=async()=>{try{for(const source of file.files){if(source.size>8*1024*1024)throw Error('單張圖片請小於 8 MB。');if(!['image/png','image/jpeg','image/webp'].includes(source.type))throw Error('請使用 PNG、JPG 或 WebP。');if(multiple&&item[key].length>=10)throw Error('每個課程最多 10 張圖片。');const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('圖片讀取失敗。'));reader.readAsDataURL(source)});await new Promise((resolve,reject)=>{const im=new Image();im.onload=resolve;im.onerror=()=>reject(Error('圖片格式無法讀取。'));im.src=src});if(multiple)item[key].push(src);else item[key]=src;changed();draw()}}catch(e){status(e.message)}file.value=''};form.append(wrap)}
function renderEditor(){const form=$('#form'),item=current();form.replaceChildren();form.hidden=!item;$('#empty').hidden=!!item;if(!item)return;const toolbar=node('div',undefined,'editor-toolbar');toolbar.append(node('h2',tab==='courses'?'編輯課程':'編輯肌膚日誌'));const del=node('button','刪除這份內容','danger');del.type='button';del.onclick=()=>{if(confirm('刪除此內容？發布前仍可重新載入官網版本復原。')){data[tab]=data[tab].filter(x=>x.id!==selected);selected=null;changed();renderEditor()}};toolbar.append(del);form.append(toolbar);field(form,item,'title',tab==='courses'?'課程名稱':'日誌名稱');if(tab==='courses'){field(form,item,'category','分類');field(form,item,'summary','一句話介紹');field(form,item,'description','完整課程介紹','textarea','只描述確實提供的內容，不自行加入未經確認的成效。');imageEditor(form,item,'images','課程圖片',true);field(form,item,'reviewNote','內部檢查備註','textarea','不會顯示在官網；資料檔為公開資料，請勿填寫個資。');if(item.reviewNote)form.append(node('p',item.reviewNote,'note'))}else{const input=field(form,{tags:(item.tags||[]).join('、')},'tags','護理標籤','text','使用「、」分隔，例如：手清粉刺、矽晶');input.oninput=()=>{item.tags=input.value.split(/[、,，]/).map(s=>s.trim()).filter(Boolean);changed()};field(form,item,'duration','紀錄間隔','text','例如：約 6 週。不填則不顯示。');const row=node('div',undefined,'row');field(row,item,'beforeDate','前次紀錄日期','text','保留原始日期寫法，例如：114.05.23');field(row,item,'afterDate','後次紀錄日期');form.append(row);imageEditor(form,item,'beforeImage','前次紀錄照片',false);field(form,item,'beforeLabel','前次照片說明');imageEditor(form,item,'afterImage','後次紀錄照片',false);field(form,item,'afterLabel','後次照片說明');field(form,item,'description','日誌文字','textarea');checkbox(form,item,'consent','已取得當事人同意公開這份照片與文字');form.append(node('p','未勾選同意公開的日誌，不會出現在官網。','readonly'))}const row=node('div',undefined,'row');field(row,item,'sortOrder','顯示順序','number','數字小的排在前面。');checkbox(row,item,'visible','顯示在官網');form.append(row)}
function add(){const id=crypto.randomUUID(),common={id,title:'',visible:false,sortOrder:data[tab].length,description:''};const item=tab==='courses'?{...common,category:'',summary:'',images:[],reviewNote:''}:{...common,tags:[],duration:'',beforeDate:'',afterDate:'',beforeImage:'',afterImage:'',beforeLabel:'',afterLabel:'',consent:false};data[tab].push(item);selected=id;changed();renderEditor();$('#form input[name=title]').focus()}
function validate(value){if(value.version!==1||!Array.isArray(value.courses)||!Array.isArray(value.journals))throw Error('內容格式不符。');const ids=new Set();for(const item of [...value.courses,...value.journals]){if(typeof item.id!=='string'||ids.has(item.id))throw Error('內容識別碼重複或不正確。');ids.add(item.id);if(!item.title?.trim())throw Error('請填寫每份內容的名稱。');if(!Number.isFinite(item.sortOrder))throw Error('顯示順序請填寫數字。');if(typeof item.visible!=='boolean')throw Error('顯示狀態格式不符。')}for(const c of value.courses){if(!c.category?.trim()||!c.description?.trim())throw Error('請填寫課程分類與介紹。');if(!Array.isArray(c.images)||c.images.length>10||c.images.some(x=>!safeImage(x)))throw Error('課程圖片格式不符。')}for(const j of value.journals){if(j.visible&&!j.consent)throw Error('顯示的日誌必須先確認當事人同意公開。');if(j.visible&&(!j.beforeDate||!j.afterDate||!j.beforeImage||!j.afterImage))throw Error('顯示的日誌請填寫兩次紀錄日期並上傳兩張照片。');for(const key of ['beforeImage','afterImage'])if(j[key]&&!safeImage(j[key]))throw Error('日誌圖片格式不符。')}return value}
function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify({data,baseSha,baseline}));status('草稿已保存在此瀏覽器，尚未發布到官網。');return true}catch{status('草稿超過瀏覽器儲存空間，請下載備份；本次頁面內容仍保留。');return false}}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='MN13-content-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function api(path,method='GET',body){const r=await fetch('https://api.github.com/repos/'+REPO+path,{method,headers:{Accept:'application/vnd.github+json','Authorization':'Bearer '+token,'X-GitHub-Api-Version':'2022-11-28',...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){if(r.status===401||r.status===403)throw Error('GitHub 權限不足或已失效，請確認權杖只授權 MN13 並允許 Contents 讀取與寫入。');if(r.status===409||r.status===422)throw Error('官網版本已變更，請先下載備份並重新載入最新內容後再編輯。');throw Error('GitHub 連線失敗（'+r.status+'），內容仍保留，請稍後重試。')}return r.json()}
function decode(base64){return new TextDecoder().decode(Uint8Array.from(atob(base64.replace(/\s/g,'')),c=>c.charCodeAt(0)))}
async function remote(ref=BRANCH){const file=await api('/contents/'+DATA_PATH+'?ref='+ref);return {data:JSON.parse(decode(file.content)),sha:file.sha}}
async function connect(){const entered=$('#token').value.trim();$('#token').value='';if(!entered){status('請先貼上 MN13 專用 GitHub 權杖。');return}setBusy(true);token=entered;try{const repo=await api('');if(repo.full_name!==REPO||repo.permissions?.push===false)throw Error('這個帳號沒有 MN13 的寫入權限。');const latest=await remote();if(dirty&&((baseSha&&baseSha!==latest.sha)||(!baseSha&&baseline!==JSON.stringify(latest.data))))throw Error('官網版本已更新。請先下載草稿備份，再重新載入官網內容。');if(!dirty){data=latest.data;renderList();renderEditor()}if(!baseSha)baseSha=latest.sha;baseline=JSON.stringify(latest.data);$('#connection-status').textContent='已連接 MN13，可發布。重新整理頁面後需再次連接。';$('#disconnect').hidden=false;$('#auth-panel').open=false;status('已連接 MN13 的發布權限。')}catch(e){token='';status(e.message)}finally{setBusy(false)}}
async function reload(){if(dirty&&!confirm('重新載入會取代未發布的修改，建議先下載備份。繼續嗎？'))return;setBusy(true);try{if(token){const latest=await remote();data=latest.data;baseSha=latest.sha}else{const r=await fetch('content.json',{cache:'no-store'});if(!r.ok)throw Error('無法載入官網內容。');data=await r.json();baseSha=null}baseline=JSON.stringify(data);localStorage.removeItem(DRAFT_KEY);dirty=false;selected=null;renderList();renderEditor();status('已載入官網內容。')}catch(e){status(e.message)}finally{setBusy(false)}}
async function publish(){if(!token){$('#auth-panel').open=true;status('請先連接 MN13 的發布權限，再發布。');$('#token').focus();return}try{validate(data)}catch(e){status(e.message);return}if(!confirm('將目前課程與肌膚日誌發布到 MN13 官網？'))return;setBusy(true);status('正在發布，請保持頁面開啟…');try{const ref=await api('/git/ref/heads/'+BRANCH),head=ref.object.sha,latest=await remote(head);if(!baseSha||latest.sha!==baseSha)throw Error('官網內容已被其他編輯更新。請下載備份，再重新載入官網內容，避免覆蓋修改。');const commit=await api('/git/commits/'+head),next=structuredClone(data),tree=[];uploads.clear();async function upload(src){if(!src.startsWith('data:'))return src;if(uploads.has(src))return uploads.get(src);const match=src.match(/^data:image\/(png|jpeg|webp);base64,(.+)$/);if(!match)throw Error('上傳圖片格式不符。');const ext=match[1]==='jpeg'?'jpg':match[1],path='MN13/media/'+crypto.randomUUID()+'.'+ext;const blob=await api('/git/blobs','POST',{content:match[2],encoding:'base64'});tree.push({path,mode:'100644',type:'blob',sha:blob.sha});const url='https://m13nbeauty.github.io/MN13/'+path;uploads.set(src,url);return url}for(const c of next.courses)c.images=await Promise.all(c.images.map(upload));for(const j of next.journals)for(const key of ['beforeImage','afterImage'])if(j[key])j[key]=await upload(j[key]);next.updatedAt=new Date().toISOString();tree.push({path:DATA_PATH,mode:'100644',type:'blob',content:JSON.stringify(next,null,2)});const result=await api('/git/trees','POST',{base_tree:commit.tree.sha,tree});const newCommit=await api('/git/commits','POST',{message:'Update MN13 courses and skin journals',tree:result.sha,parents:[head]});await api('/git/refs/heads/'+BRANCH,'PATCH',{sha:newCommit.sha,force:false});data=next;baseSha=result.tree.find(x=>x.path===DATA_PATH)?.sha||null;if(!baseSha){const latestFile=await remote();baseSha=latestFile.sha}baseline=JSON.stringify(data);dirty=false;localStorage.removeItem(DRAFT_KEY);renderList();renderEditor();status('已發布到 MN13。GitHub Pages 更新需要一點時間；請稍後重新整理官網確認。')}catch(e){status(e.message+'\n本次修改仍保留，尚未確認發布成功。')}finally{setBusy(false)}}
$('#form').onsubmit=e=>e.preventDefault();$('#add').onclick=add;$('#search').oninput=renderList;$('#save').onclick=saveDraft;$('#export').onclick=exportData;$('#connect').onclick=connect;$('#disconnect').onclick=()=>{token='';$('#connection-status').textContent='已中斷連接。';$('#disconnect').hidden=true;status('已中斷發布權限，編輯內容仍保留。')};$('#reload').onclick=reload;$('#publish').onclick=publish;document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{tab=button.dataset.tab;selected=null;$('#search').value='';$('#list-title').textContent=tab==='courses'?'課程列表':'日誌列表';document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderList();renderEditor()});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{const response=await fetch('content.json',{cache:'no-store'});if(!response.ok)throw Error('無法讀取官網內容。');data=await response.json();baseline=JSON.stringify(data);const raw=localStorage.getItem(DRAFT_KEY);if(raw){try{const draft=JSON.parse(raw);if(draft.data?.version===1){data=draft.data;baseSha=draft.baseSha;baseline=draft.baseline||'';dirty=true;status('已還原此瀏覽器的草稿，尚未發布。')}}catch{status('草稿無法讀取，已載入官網內容。')}}else status('已載入官網內容，選一份內容開始編輯。');renderList();renderEditor()}catch(e){status(e.message);$('#add').disabled=true}})();
